Vagrant.configure("2") do |config|
    config.vm.box = "windows-2016-amd64"
    config.vm.define "test-node-one"
    config.vm.hostname = "test-node-one"

    config.vm.provider :virtualbox do |v, override|
        v.linked_clone = true
        v.cpus = 2
        v.memory = 2048
        v.customize ["modifyvm", :id, "--vram", 64]
        v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    end

    config.vm.network "private_network", ip: "192.168.56.3"

    config.vm.provision "windows-sysprep"
    config.vm.provision "shell", path: "provision/locale.ps1"
    config.vm.provision "shell", path: "provision/add-to-domain.ps1"
    config.vm.provision "reload"
end
